WIP conversion of testReleaseHelp script from csh to bash

diff --git a/util/buildRelease/testReleaseHelp b/util/buildRelease/testReleaseHelp
--- a/util/buildRelease/testReleaseHelp
+++ b/util/buildRelease/testReleaseHelp
@@ -1,80 +1,91 @@
-#!/bin/csh
+#!/bin/bash
 
 #
-# unsetenv normal Chapel environment variables
+# unset normal Chapel environment variables
 #
-unsetenv CHPL_HOME
-unsetenv CHPL_NIGHTLY_LOGDIR
-unsetenv CHPL_DEVELOPER
-unsetenv CHPL_HOST_PLATFORM
-unsetenv CHPL_TARGET_PLATFORM
-unsetenv CHPLDEVTMP
+unset CHPL_HOME
+unset CHPL_NIGHTLY_LOGDIR
+unset CHPL_DEVELOPER
+unset CHPL_HOST_PLATFORM
+unset CHPL_TARGET_PLATFORM
+unset CHPLDEVTMP
 
-set mymake = $argv[1]
+# Directory of script, will not work if script is a symlink
+DIR=$(cd "$(dirname "${filepath}")" && pwd)
+
+# Shallow test to see if we are in the correct directory
+# Just probe to see if we have a few essential subdirectories --
+# indicating that we are probably in a Chapel root directory.
+chpl_home=$( cd $DIR/../../ && pwd )
+if [ ! -d "$chpl_home/util" ] || [ ! -d "$chpl_home/compiler" ] || [ ! -d "$chpl_home/runtime" ] || [ ! -d "$chpl_home/modules" ]; then
+    # Chapel home is assumed to be one directory up from setenvchpl.bash script
+    echo "Error: \$CHPL_HOME is not where it is expected"
+    return 1
+fi
 
 # Number of logical processes on current system. Will be used as number of jobs
 # when calling make with parallel execution.
-set num_procs = `${0:h}/chpl-make-cpu_count`
+num_procs=$(${DIR}/chpl-make-cpu_count)
 
 #
 # execute actions specified in README
 #
-if ( $#argv == 0 ) then
+if [ $# -eq 0 ]; then
     echo "usage: $argv[0] <make utility>"
-    exit(1);
-endif
-source util/quickstart/setchplenv.csh
-set tmpstatus = $status
-if ($tmpstatus != 0) then
-    echo "ERROR: source of setchplenv.csh failed"
-    exit($tmpstatus)
-endif
+    exit 1
+fi
+source util/quickstart/setchplenv.bash
+tmpstatus=$status
+if [ $tmpstatus != 0 ]; then
+    echo "ERROR: source of setchplenv.bash failed"
+    exit $tmpstatus
+fi
 $mymake -j$num_procs
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: make failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 rehash   # required for csh only; if we convert this to bash, drop this
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: make failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 $mymake check
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: make check failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 chpl -o hello examples/hello.chpl
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: compilation of hello.chpl failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 ./hello
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: execution of hello failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 
 # Build chpldoc and run chpldoc-check.
 $mymake -j$num_procs chpldoc
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: make chpldoc failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 rehash   # required for csh only; if we convert this to bash, drop this
 
 $mymake check-chpldoc
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: make check-chpldoc failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 
 
 # Calculate expected version string from version_num.h.
@@ -86,14 +97,14 @@ set expected_version_string="$major.$minor.$patch"
 # Test chpl --version for expected string version.
 set version_string = `chpl --version | grep 'version' | cut -d' ' -f 3`
 set versionstatus = $status
-if ($versionstatus != 0) then
+if ($versionstatus != 0); then
     echo "ERROR: execution of chpl --version failed"
-    exit($versionstatus)
-endif
-if ($version_string != "$expected_version_string") then
+    exit $versionstatus
+fi
+if ($version_string != "$expected_version_string"); then
     echo "ERROR: unexpected version string, received '$version_string' expected '$expected_version_string'"
-    exit(1)
-endif
+    exit 1
+fi
 
 #
 # run make in examples directory
@@ -101,10 +112,10 @@ endif
 cd examples
 $mymake -j$num_procs
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: compiling examples with 'make' failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 cd ..
 
 
@@ -113,23 +124,23 @@ cd ..
 #
 cd examples
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: cd into examples failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 
 set start_test_flags = ''
-if ($?CHPL_TEST_RELEASE_NORECURSE) then
+if ($?CHPL_TEST_RELEASE_NORECURSE); then
     set start_test_flags = ${start_test_flags}' --norecurse'
-endif
+fi
 
 ./start_test ${start_test_flags} -logfile Logs/testReleaseHelp.log
 
-endif
+fi
 set tmpstatus = $status
-if ($tmpstatus != 0) then
+if ($tmpstatus != 0); then
     echo "ERROR: testing of examples failed"
-    exit($tmpstatus)
-endif
+    exit $tmpstatus
+fi
 
-exit(0)
+exit 0
